Repository Developurr-inc/personal-cleaner-crm, pull requests merged in 2023-10, with the labels that each got.

#57 Edited ShippingFixture.cs and ShippingTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Shipping/ShippingTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Constants/Constants.Shipping.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Shipping/ShippingAssertion.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Shipping/ShippingFixture.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Shipping/ShippingGenerator.cs
Labels: bug

#56 Feature/create shipping application usecase
  src/Orderly.Application/UseCase/Shipping/CreateShipping/CreateShippingInput.cs
  src/Orderly.Application/UseCase/Shipping/CreateShipping/CreateShippingOutput.cs
  src/Orderly.Application/UseCase/Shipping/CreateShipping/CreateShippingUseCase.cs
  src/Orderly.Application/UseCase/Shipping/DeleteShipping/DeleteShippingInput.cs
  src/Orderly.Application/UseCase/Shipping/DeleteShipping/DeleteShippingOutput.cs
  src/Orderly.Application/UseCase/Shipping/DeleteShipping/DeleteShippingUseCase.cs
  src/Orderly.Application/UseCase/Shipping/GetShipping/GetShippingInput.cs
  src/Orderly.Application/UseCase/Shipping/GetShipping/GetShippingOutput.cs
  src/Orderly.Application/UseCase/Shipping/GetShipping/GetShippingUseCase.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Customer/ValueObjects/CustomerIdTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Manager/ValueObjects/ManagerIdTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Order/ValueObjects/LineItemIdTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Order/ValueObjects/OrderIdTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Product/ValueObjects/ProductIdTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/SalesConsultant/ValueObjects/SalesConsultantId.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Shipping/ValueObjects/ShippingIdTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Manager/ManagerAssertion.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/ProductId/ProductIdAssertion.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/ProductId/ProductIdFixture.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/ProductId/ProductIdGenerator.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/ShippingId/ShippingIdAssertion.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/ShippingId/ShippingIdFixture.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/ShippingId/ShippingIdGenerator.cs
Labels: new feature

#58 Edit SalesConsultant.cs, SalesConsultantFixture.cs and SalesConsultan…
  src/Orderly.Domain/SalesConsultant/SalesConsultant.cs
  tests/UnitTests/Orderly.Domain.UnitTests/SalesConsultant/SalesConsultantTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Constants/Constants.SalesConsultant.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/SalesConsultant/SalesConsultantAssertion.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/SalesConsultant/SalesConsultantFixture.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/SalesConsultant/SalesConsultantGenerator.cs
Labels: bug

#65 Edit CustomerFixture.cs and CustomerTest.cs. Delete CustomerAssertion…
  tests/UnitTests/Orderly.Domain.UnitTests/Customer/CustomerTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Constants/Constants.Customer.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Constants/Constants.SalesConsultantId.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Customer/CustomerAssertion.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Customer/CustomerFixture.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Customer/CustomerGenerator.cs
Labels: bug

#64 Created application Order UseCase
  src/Orderly.Application/UseCase/Order/CreateOrder/CreateOrderInput.cs
  src/Orderly.Application/UseCase/Order/CreateOrder/CreateOrderOutput.cs
  src/Orderly.Application/UseCase/Order/CreateOrder/CreateOrderUseCase.cs
  src/Orderly.Application/UseCase/Order/DeleteOrder/DeleteOrderInput.cs
  src/Orderly.Application/UseCase/Order/DeleteOrder/DeleteOrderOutput.cs
  src/Orderly.Application/UseCase/Order/DeleteOrder/DeleteOrderUseCase.cs
  src/Orderly.Application/UseCase/Order/GetOrder/GetOrderInput.cs
  src/Orderly.Application/UseCase/Order/GetOrder/GetOrderOutput.cs
  src/Orderly.Application/UseCase/Order/GetOrder/GetOrderUseCase.cs
Labels: new feature

#63 fix discount tests
  tests/UnitTests/Orderly.Domain.UnitTests/Order/ValueObjects/DiscountTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Constants/Constants.Discount.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Discount/DiscountAssertion.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Discount/DiscountFixture.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Discount/DiscountGenerator.cs
Labels: bug

#66 Edit QuantityFixture.cs and QuantityTest.cs. Delete QuantityAssertion…
  src/Orderly.Domain/Order/Validators/QuantityValidatorConfig.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Order/ValueObjects/QuantityTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Constants/Constants.Quantity.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Quantity/QuantityAssertion.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Quantity/QuantityFixture.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Quantity/QuantityGenerator.cs
Labels: bug

#67 Fix Manager tests
  tests/UnitTests/Orderly.Domain.UnitTests/Manager/ManagerTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Constants/Constants.Manager.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Manager/ManagerAssertion.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Manager/ManagerFixture.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Manager/ManagerGenerator.cs
Labels: bug

#68 Edit OrderFixture.cs and OrderTest.cs. Delete OrderAssertion.cs and O…
  tests/UnitTests/Orderly.Domain.UnitTests/Order/OrderTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Constants/Constants.CustomerId.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Order/OrderAssertion.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Order/OrderFixture.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Order/OrderGenerator.cs
Labels: bug

#52 Feature/application layer tests
  Orderly.sln
  tests/UnitTests/Orderly.Application.UnitTests/GlobalUsings.cs
  tests/UnitTests/Orderly.Application.UnitTests/Orderly.Application.UnitTests.csproj
  tests/UnitTests/Orderly.Application.UnitTests/TestUtils/CreateCustomer/CreateCustomerFixture.cs
  tests/UnitTests/Orderly.Application.UnitTests/UseCase/Customer/CreateCustomer/CreateCustomerTest.cs
Labels: bug, enhancement

#72 Feature/get shipping use case test
  tests/UnitTests/Orderly.Application.UnitTests/TestUtils/CreateShipping/CreateShippingFixture.cs
  tests/UnitTests/Orderly.Application.UnitTests/UseCase/Shipping/CreateShipping/CreateShippingTest.cs
Labels: new feature

#70 CreateShipping UseCase Application Tests
  tests/UnitTests/Orderly.Application.UnitTests/TestUtils/CreateShipping/CreateShippingFixture.cs
  tests/UnitTests/Orderly.Application.UnitTests/UseCase/CreateShipping/CreateShippingTest.cs
Labels: new feature

#71 Create product usecase tests
  tests/UnitTests/Orderly.Application.UnitTests/TestUtils/CreateProduct/CreateProductFixture.cs
  tests/UnitTests/Orderly.Application.UnitTests/UseCase/Product/CreateProduct/CreateProductTest.cs
Labels: new feature

#74 Add create, get and delete Customer application
  src/Developurr.Orderly.Application/Command/Customer/CreateCustomer/CreateCustomerOutput.cs
  src/Developurr.Orderly.Application/Command/Customer/DeleteCustomer/DeleteCustomerInput.cs
  src/Developurr.Orderly.Application/Command/Customer/DeleteCustomer/DeleteCustomerOutput.cs
  src/Developurr.Orderly.Application/Command/Customer/DeleteCustomer/DeleteCustomerUseCase.cs
  src/Developurr.Orderly.Application/Query/Customer/GetCustomerInput.cs
  tests/UnitTests/Developurr.Orderly.Application.UnitTests/Developurr.Orderly.Application.UnitTests.csproj
  tests/UnitTests/Developurr.Orderly.Application.UnitTests/TestUtils/CreateProduct/CreateProductFixture.cs
  tests/UnitTests/Developurr.Orderly.Application.UnitTests/TestUtils/GetProduct/GetProductFixture.cs
  tests/UnitTests/Developurr.Orderly.Application.UnitTests/UseCase/Product/CreateProduct/CreateProductTest.cs
  tests/UnitTests/Developurr.Orderly.Application.UnitTests/UseCase/Product/GetProduct/GetProductTest.cs
  tests/UnitTests/Developurr.Orderly.Domain.UnitTests/TestUtils/Constants/Constants.ProductId.cs
Labels: new feature

#79 Feature/improve application interfaces
  src/Developurr.Orderly.Application/Command/Customer/CreateCustomer/CreateCustomerInput.cs
  src/Developurr.Orderly.Application/Command/Customer/CreateCustomer/CreateCustomerUseCase.cs
  src/Developurr.Orderly.Application/Command/Customer/DeleteCustomer/DeleteCustomerUseCase.cs
  src/Developurr.Orderly.Application/Command/ICommand.cs
  src/Developurr.Orderly.Application/Command/IUseCase.cs
  src/Developurr.Orderly.Application/Command/Order/CloseOrder/CloseOrderUseCase.cs
  src/Developurr.Orderly.Application/Command/Order/OpenOrder/OpenOrderUseCase.cs
  src/Developurr.Orderly.Application/IUseCase.cs
  src/Developurr.Orderly.Application/Query/Customer/GetCustomer/GetCustomerInput.cs
  src/Developurr.Orderly.Application/Query/Customer/GetCustomer/GetCustomerOutput.cs
  src/Developurr.Orderly.Application/Query/Customer/GetCustomer/GetCustomerUseCase.cs
  src/Developurr.Orderly.Application/Query/Customer/GetCustomerInput.cs
  src/Developurr.Orderly.Application/Query/IQuery.cs
  src/Developurr.Orderly.Application/Query/Order/GetOrder/GetOrderInput.cs
  src/Developurr.Orderly.Application/Query/Order/GetOrder/GetOrderOutput.cs
  src/Developurr.Orderly.Application/Query/Order/GetOrder/GetOrderUseCase.cs
  src/Developurr.Orderly.Application/Query/Order/GetOrderInput.cs
  src/Developurr.Orderly.Application/Query/Order/GetOrderOutput.cs
  src/Developurr.Orderly.Application/Query/Order/GetOrderUseCase.cs
  src/Developurr.Orderly.Application/UseCase/Customer/CreateCustomer/CreateCustomerOutput.cs
  src/Developurr.Orderly.Application/UseCase/Customer/GetCustomer/GetCustomerInput.cs
  src/Developurr.Orderly.Application/UseCase/IUnitOfWork.cs
  src/Developurr.Orderly.Application/UseCase/IUseCase.cs
  src/Developurr.Orderly.Application/UseCase/Manager/CreateManager/CreateManagerUseCase.cs
  src/Developurr.Orderly.Application/UseCase/Manager/DeleteManager/DeleteManagerUseCase.cs
  src/Developurr.Orderly.Application/UseCase/Manager/GetManager/GetManagerUseCase.cs
  src/Developurr.Orderly.Application/UseCase/Order/CreateOrder/CreateOrderInput.cs
  src/Developurr.Orderly.Application/UseCase/Order/CreateOrder/CreateOrderOutput.cs
  src/Developurr.Orderly.Application/UseCase/Order/CreateOrder/CreateOrderUseCase.cs
  src/Developurr.Orderly.Application/UseCase/Order/DeleteOrder/DeleteOrderInput.cs
  src/Developurr.Orderly.Application/UseCase/Order/DeleteOrder/DeleteOrderOutput.cs
  src/Developurr.Orderly.Application/UseCase/Order/DeleteOrder/DeleteOrderUseCase.cs
  src/Developurr.Orderly.Application/UseCase/Order/GetOrder/GetOrderInput.cs
  src/Developurr.Orderly.Application/UseCase/Order/GetOrder/GetOrderOutput.cs
  src/Developurr.Orderly.Application/UseCase/Order/GetOrder/GetOrderUseCase.cs
  src/Developurr.Orderly.Application/UseCase/Product/CreateProduct/CreateProductUseCase.cs
  src/Developurr.Orderly.Application/UseCase/Product/DeleteProduct/DeleteProductUseCase.cs
  src/Developurr.Orderly.Application/UseCase/Product/GetProduct/GetProductUseCase.cs
  src/Developurr.Orderly.Application/UseCase/SalesConsultant/CreateSalesConsultant/CreateSalesConsultantUseCase.cs
  src/Developurr.Orderly.Application/UseCase/SalesConsultant/DeleteSalesConsultant/DeleteSalesConsultantUseCase.cs
  src/Developurr.Orderly.Application/UseCase/SalesConsultant/GetSalesConsultant/GetSalesConsultantUseCase.cs
  src/Developurr.Orderly.Application/UseCase/Shipping/CreateShipping/CreateShippingUseCase.cs
  src/Developurr.Orderly.Application/UseCase/Shipping/DeleteShipping/DeleteShippingUseCase.cs
  src/Developurr.Orderly.Application/UseCase/Shipping/GetShipping/GetShippingUseCase.cs
  tests/UnitTests/Developurr.Orderly.Application.UnitTests/UseCase/Order/OpenOrder/OpenOrderTest.cs
  tests/UnitTests/Developurr.Orderly.Application.UnitTests/UseCase/Product/CreateProduct/CreateProductTest.cs
Labels: enhancement

#85 Feature/customer application tests delete
  src/Developurr.Orderly.Application/Command/Customer/DeleteCustomer/DeleteCustomerUseCase.cs
  src/Developurr.Orderly.Application/Developurr.Orderly.Application.csproj
  src/Developurr.Orderly.Domain/Customer/Customer.cs
  src/Developurr.Orderly.Domain/Developurr.Orderly.Domain.csproj
  tests/UnitTests/Developurr.Orderly.Application.UnitTests/Developurr.Orderly.Application.UnitTests.csproj
  tests/UnitTests/Developurr.Orderly.Application.UnitTests/TestUtils/CreateCustomer/CreateCustomerFixture.cs
  tests/UnitTests/Developurr.Orderly.Application.UnitTests/TestUtils/DeleteCustomer/DeleteCustomerFixture.cs
  tests/UnitTests/Developurr.Orderly.Application.UnitTests/UseCase/Customer/CreateCustomer/CreateCustomerTest.cs
  tests/UnitTests/Developurr.Orderly.Application.UnitTests/UseCase/Customer/DeleteCustomer/DeleteCustomerTest.cs
  tests/UnitTests/Developurr.Orderly.Domain.UnitTests/Developurr.Orderly.Domain.UnitTests.csproj
Labels: new feature

#81 Add customer tests application create
  src/Developurr.Orderly.Application/Developurr.Orderly.Application.csproj
  src/Developurr.Orderly.Domain/Developurr.Orderly.Domain.csproj
  tests/UnitTests/Developurr.Orderly.Application.UnitTests/Developurr.Orderly.Application.UnitTests.csproj
  tests/UnitTests/Developurr.Orderly.Application.UnitTests/TestUtils/CreateCustomer/CreateCustomerFixture.cs
  tests/UnitTests/Developurr.Orderly.Application.UnitTests/UseCase/Customer/CreateCustomer/CreateCustomerTest.cs
  tests/UnitTests/Developurr.Orderly.Domain.UnitTests/Developurr.Orderly.Domain.UnitTests.csproj
Labels: new feature

#90 Update ValidationRules.cs
  src/Developurr.Orderly.Domain/Validation/ValidationRules.cs
Labels: bug

#96 Conserto do bug do preço
  tests/UnitTests/Developurr.Orderly.Domain.UnitTests/Common/ValueObjects/PriceTest.cs
  tests/UnitTests/Developurr.Orderly.Domain.UnitTests/TestUtils/Price/PriceFixture.cs
Labels: bug

#92 Fix GetById should be able to return null
  src/Developurr.Orderly.Domain/SeedWork/IRepository.cs
Labels: bug

#110 Add NotFoundException.cs in Application
  src/Developurr.Orderly.Application/Command/Customer/DeleteCustomer/DeleteCustomerUseCase.cs
  src/Developurr.Orderly.Application/Command/Order/CloseOrder/CloseOrderUseCase.cs
  src/Developurr.Orderly.Application/Exceptions/NotFoundException.cs
  tests/UnitTests/Developurr.Orderly.Application.UnitTests/UseCase/Customer/DeleteCustomer/DeleteCustomerTest.cs
  tests/UnitTests/Developurr.Orderly.Application.UnitTests/UseCase/Order/CloseOrder/CloseOrderTest.cs
Labels: new feature

#108 Remove StringFixture.cs and StringGenerator.cs
  tests/UnitTests/Developurr.Orderly.Domain.UnitTests/TestUtils/String/StringFixture.cs
  tests/UnitTests/Developurr.Orderly.Domain.UnitTests/TestUtils/String/StringGenerator.cs
  tests/UnitTests/Developurr.Orderly.Domain.UnitTests/Validation/ValidationRulesTest.cs
Labels: bug

#106 Add delete vendor application tests
  src/Developurr.Orderly.Application/Command/Vendor/DeleteVendor/DeleteVendorUseCase.cs
  src/Developurr.Orderly.Domain/Vendor/Vendor.cs
  tests/UnitTests/Developurr.Orderly.Application.UnitTests/TestUtils/DeleteVendor/DeleteVendorFixture.cs
  tests/UnitTests/Developurr.Orderly.Application.UnitTests/TestUtils/GetVendor/GetVendorFixture.cs
  tests/UnitTests/Developurr.Orderly.Application.UnitTests/UseCase/Vendor/DeleteVendor/DeleteVendorTest.cs
  tests/UnitTests/Developurr.Orderly.Application.UnitTests/UseCase/Vendor/GetVendor/GetVendorTest.cs
Labels: new feature

#109 Add NonEmptyTextTest.cs and OptionalTextTest.cs
  src/Developurr.Orderly.Domain/Shared/ValueObjects/NonEmptyText.cs
  src/Developurr.Orderly.Domain/Shared/ValueObjects/OptionalText.cs
  tests/UnitTests/Developurr.Orderly.Domain.UnitTests/Shared/ValueObjects/NonEmptyTextTest.cs
  tests/UnitTests/Developurr.Orderly.Domain.UnitTests/Shared/ValueObjects/OptionalTextTest.cs
  tests/UnitTests/Developurr.Orderly.Domain.UnitTests/TestUtils/NonEmptyText/NonEmptyTextFixture.cs
  tests/UnitTests/Developurr.Orderly.Domain.UnitTests/TestUtils/OptionalText/OptionalTextFixture.cs
  tests/UnitTests/Developurr.Orderly.Domain.UnitTests/TestUtils/Price/PriceFixture.cs
  tests/UnitTests/Developurr.Orderly.Domain.UnitTests/TestUtils/Quantity/QuantityFixture.cs
Labels: new feature

#104 Adicionado noneemptytext e optionaltext no dominio.
  src/Developurr.Orderly.Application/Command/Customer/DeleteCustomer/DeleteCustomerUseCase.cs
  src/Developurr.Orderly.Domain/Customer/Customer.cs
  src/Developurr.Orderly.Domain/Manager/Manager.cs
  src/Developurr.Orderly.Domain/Order/Order.cs
  src/Developurr.Orderly.Domain/Shipping/Shipping.cs
  src/Developurr.Orderly.Domain/Vendor/Vendor.cs
  tests/UnitTests/Developurr.Orderly.Application.UnitTests/UseCase/Customer/DeleteCustomer/DeleteCustomerTest.cs
  tests/UnitTests/Developurr.Orderly.Application.UnitTests/UseCase/Order/CloseOrder/CloseOrderTest.cs
  tests/UnitTests/Developurr.Orderly.Domain.UnitTests/Customer/CustomerTest.cs
  tests/UnitTests/Developurr.Orderly.Domain.UnitTests/Manager/ManagerTest.cs
  tests/UnitTests/Developurr.Orderly.Domain.UnitTests/Shipping/ShippingTest.cs
  tests/UnitTests/Developurr.Orderly.Domain.UnitTests/Vendor/VendorTest.cs
Labels: bug

#117 Criados os testes activestatus para o Package
  src/Developurr.Orderly.Domain/Package/Package.cs
  tests/UnitTests/Developurr.Orderly.Domain.UnitTests/Package/PackageTest.cs
Labels: bug

#114 Criados testes de activestatus para o Manager
  src/Developurr.Orderly.Domain/Manager/Manager.cs
  tests/UnitTests/Developurr.Orderly.Domain.UnitTests/Manager/ManagerTest.cs
  tests/UnitTests/Developurr.Orderly.Domain.UnitTests/TestUtils/Manager/ManagerFixture.cs
Labels: bug

#120 Modificados campos de Customer.cs e Shipping.cs para português.
  src/Developurr.Orderly.Application/Query/Customer/GetCustomer/GetCustomerUseCase.cs
  src/Developurr.Orderly.Application/UseCase/Shipping/GetShipping/GetShippingUseCase.cs
  src/Developurr.Orderly.Domain/Customer/Customer.cs
  src/Developurr.Orderly.Domain/Shipping/Shipping.cs
  tests/UnitTests/Developurr.Orderly.Domain.UnitTests/Shipping/ShippingTest.cs
Labels: bug

#121 Create ZipCode value object
  src/Developurr.Orderly.Domain/Shared/ValueObjects/Validators/ZipCodeValidator.cs
  src/Developurr.Orderly.Domain/Shared/ValueObjects/Validators/ZipCodeValidatorConfig.cs
  src/Developurr.Orderly.Domain/Shared/ValueObjects/ZipCode.cs
Labels: new feature

#118 Add shippingdeactivate
  src/Developurr.Orderly.Domain/Shipping/Shipping.cs
  tests/UnitTests/Developurr.Orderly.Domain.UnitTests/Shipping/ShippingTest.cs
Labels: new feature

#127 Testes movidos da pasta common para shared.
  tests/UnitTests/Developurr.Orderly.Domain.UnitTests/Shared/ValueObjects/AddressTest.cs
  tests/UnitTests/Developurr.Orderly.Domain.UnitTests/Shared/ValueObjects/CnpjTest.cs
  tests/UnitTests/Developurr.Orderly.Domain.UnitTests/Shared/ValueObjects/CpfTest.cs
  tests/UnitTests/Developurr.Orderly.Domain.UnitTests/Shared/ValueObjects/EmailTest.cs
  tests/UnitTests/Developurr.Orderly.Domain.UnitTests/Shared/ValueObjects/PhoneTest.cs
  tests/UnitTests/Developurr.Orderly.Domain.UnitTests/Shared/ValueObjects/PriceTest.cs
Labels: bug

#125 Implementados construtores privados nas entidades e objetos de valor
  src/Developurr.Orderly.Domain/Category/Category.EF.cs
  src/Developurr.Orderly.Domain/Category/Category.cs
  src/Developurr.Orderly.Domain/Category/ValueObjects/CategoryId.cs
  src/Developurr.Orderly.Domain/Customer/Customer.EF.cs
  src/Developurr.Orderly.Domain/Customer/Customer.cs
  src/Developurr.Orderly.Domain/Customer/ValueObjects/CustomerId.cs
  src/Developurr.Orderly.Domain/Manager/Manager.EF.cs
  src/Developurr.Orderly.Domain/Manager/Manager.cs
  src/Developurr.Orderly.Domain/Manager/ValueObjects/ManagerId.cs
  src/Developurr.Orderly.Domain/Order/Entities/LineItem.EF.cs
  src/Developurr.Orderly.Domain/Order/Entities/LineItem.cs
  src/Developurr.Orderly.Domain/Order/Order.EF.cs
  src/Developurr.Orderly.Domain/Order/Order.cs
  src/Developurr.Orderly.Domain/Order/ValueObjects/Discount.cs
  src/Developurr.Orderly.Domain/Order/ValueObjects/LineItemId.cs
  src/Developurr.Orderly.Domain/Order/ValueObjects/OrderId.cs
  src/Developurr.Orderly.Domain/Package/Package.EF.cs
  src/Developurr.Orderly.Domain/Package/Package.cs
  src/Developurr.Orderly.Domain/Package/ValueObjects/PackageId.cs
  src/Developurr.Orderly.Domain/Product/Product.EF.cs
  src/Developurr.Orderly.Domain/Product/Product.cs
  src/Developurr.Orderly.Domain/Product/ValueObjects/ProductId.cs
  src/Developurr.Orderly.Domain/Product/ValueObjects/Sku.cs
  src/Developurr.Orderly.Domain/Shared/ValueObjects/ActiveStatus.cs
  src/Developurr.Orderly.Domain/Shared/ValueObjects/Address.cs
  src/Developurr.Orderly.Domain/Shared/ValueObjects/Cnpj.cs
  src/Developurr.Orderly.Domain/Shared/ValueObjects/Cpf.cs
  src/Developurr.Orderly.Domain/Shared/ValueObjects/Email.cs
  src/Developurr.Orderly.Domain/Shared/ValueObjects/NonEmptyText.cs
  src/Developurr.Orderly.Domain/Shared/ValueObjects/OptionalText.cs
  src/Developurr.Orderly.Domain/Shared/ValueObjects/Phone.cs
  src/Developurr.Orderly.Domain/Shared/ValueObjects/Price.cs
  src/Developurr.Orderly.Domain/Shared/ValueObjects/Quantity.cs
  src/Developurr.Orderly.Domain/Shared/ValueObjects/ZipCode.cs
  src/Developurr.Orderly.Domain/Shipping/Shipping.EF.cs
  src/Developurr.Orderly.Domain/Shipping/Shipping.cs
  src/Developurr.Orderly.Domain/Shipping/ValueObjects/ShippingId.cs
  src/Developurr.Orderly.Domain/Vendor/ValueObjects/VendorId.cs
  src/Developurr.Orderly.Domain/Vendor/Vendor.EF.cs
  src/Developurr.Orderly.Domain/Vendor/Vendor.cs
Labels: bug

#130 Criado diretório do EndToEndTests
  Orderly.sln
  tests/Developurr.Orderly.API.REST.EndToEndTests/Developurr.Orderly.API.REST.EndToEndTests.csproj
  tests/Developurr.Orderly.API.REST.EndToEndTests/GlobalUsings.cs
Labels: new feature
