Repository Developurr-inc/personal-cleaner-crm, pull requests merged in 2023-09, with the labels that each got.

#6 Feature/create validation tests
  .gitignore
  Orderly.sln
  src/Orderly.Domain/Common/ValueObjects/Address.cs
  src/Orderly.Domain/Common/ValueObjects/Cnpj.cs
  src/Orderly.Domain/Common/ValueObjects/Cpf.cs
  src/Orderly.Domain/Common/ValueObjects/Email.cs
  src/Orderly.Domain/Common/ValueObjects/Phone.cs
  src/Orderly.Domain/Common/ValueObjects/Price.cs
  src/Orderly.Domain/Common/ValueObjects/Validators/AddressValidator.cs
  src/Orderly.Domain/Common/ValueObjects/Validators/CnpjValidator.cs
  src/Orderly.Domain/Common/ValueObjects/Validators/CpfValidator.cs
  src/Orderly.Domain/Common/ValueObjects/Validators/EmailValidator.cs
  src/Orderly.Domain/Common/ValueObjects/Validators/PhoneValidator.cs
  src/Orderly.Domain/Common/ValueObjects/Validators/PriceValidator.cs
  src/Orderly.Domain/Exceptions/EntityValidationException.cs
  src/Orderly.Domain/Orderly.Domain.csproj
  src/Orderly.Domain/SeedWork/AggregateRoot.cs
  src/Orderly.Domain/SeedWork/Entity.cs
  src/Orderly.Domain/SeedWork/IDomainEvent.cs
  src/Orderly.Domain/SeedWork/IRepository.cs
  src/Orderly.Domain/SeedWork/IUnitOfWork.cs
  src/Orderly.Domain/SeedWork/ValueObject.cs
  src/Orderly.Domain/Validation/IValidator.cs
  src/Orderly.Domain/Validation/ValidationRules.cs
  src/Orderly.Domain/Validation/Validator.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Common/ValueObjects/AddressTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Common/ValueObjects/CnpjTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Common/ValueObjects/CpfTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Common/ValueObjects/EmailTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Common/ValueObjects/PhoneTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Common/ValueObjects/PriceTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/GlobalUsings.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Orderly.Domain.UnitTests.csproj
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Address/AddressAssertion.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Address/AddressFixture.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Address/AddressGenerator.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/BaseFixture.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/BaseGenerator.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Cnpj/CnpjAssertion.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Cnpj/CnpjFixture.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Cnpj/CnpjGenerator.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Cpf/CpfAssertion.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Cpf/CpfFixture.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Cpf/CpfGenerator.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Email/EmailAssertion.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Email/EmailFixture.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Email/EmailGenerator.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Phone/PhoneAssertion.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Phone/PhoneFixture.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Phone/PhoneGenerator.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Price/PriceAssertion.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Price/PriceFixture.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Price/PriceGenerator.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/String/StringFixture.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/String/StringGenerator.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/ValidationRules/ValidationRulesFixture.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Validation/ValidationRulesTest.cs
Labels: enhancement

#4 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: documentation

#10 Created base customer files
  src/Orderly.Domain/Customer/Customer.cs
  src/Orderly.Domain/Customer/Validators/CustomerValidator.cs
  src/Orderly.Domain/Customer/ValueObjects/CustomerId.cs
  src/Orderly.Domain/SeedWork/AggregateRoot.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Customer/CustomerTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Customer/CustomerAssertion.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Customer/CustomerFixture.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Customer/CustomerGenerator.cs
Labels: new feature

#14 Created IAggregateRoot interface
  src/Orderly.Domain/SeedWork/IAggregateRoot.cs
Labels: bug

#13 Renamed variable
  src/Orderly.Domain/Validation/ValidationRules.cs
Labels: bug

#11 Base commit.
  src/Orderly.Domain/Manager/Manager.cs
  src/Orderly.Domain/Manager/Validators/ManagerValidator.cs
  src/Orderly.Domain/Manager/ValueObjects/ManagerId.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Manager/ManagerTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Manager/ManagerAssertion.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Manager/ManagerFixture.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Manager/ManagerGenerator.cs
Labels: new feature

#8 Create dotnet.yml
  .github/workflows/dotnet.yml
Labels: enhancement, new feature

#16 Removed wrong assertion
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Customer/CustomerAssertion.cs
Labels: bug

#15 Rename test variables.
  tests/UnitTests/Orderly.Domain.UnitTests/Common/ValueObjects/AddressTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Common/ValueObjects/CnpjTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Common/ValueObjects/CpfTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Common/ValueObjects/EmailTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Common/ValueObjects/PhoneTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Common/ValueObjects/PriceTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Validation/ValidationRulesTest.cs
Labels: bug

#12 Base Commit
  src/Orderly.Domain/SalesConsultant/SalesConsultant.cs
  src/Orderly.Domain/SalesConsultant/Validators/SalesConsultantValidator.cs
  src/Orderly.Domain/SalesConsultant/ValueObjects/SalesConsultantId.cs
  tests/UnitTests/Orderly.Domain.UnitTests/SalesConsultant/SalesConsultantTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/SalesConsultant/SalesConsultantAssertion.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/SalesConsultant/SalesConsultantFixture.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/SalesConsultant/SalesConsultantGenerator.cs
Labels: new feature

#20 Create dependabot.yml
  .github/dependabot.yml
Labels: enhancement, new feature

#19 Create codeql.yml
  .github/codeql/codeql-config.yml
  .github/workflows/codeql.yml
Labels: enhancement, new feature

#29 Update dependabot.yml
  .github/dependabot.yml
Labels: enhancement, dependencies

#24 fix/standardized-new-way-to-validate-domain-validation-exception
  tests/UnitTests/Orderly.Domain.UnitTests/Common/ValueObjects/AddressTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Common/ValueObjects/CnpjTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Common/ValueObjects/CpfTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Common/ValueObjects/EmailTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Common/ValueObjects/PhoneTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Common/ValueObjects/PriceTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Customer/CustomerTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Manager/ManagerTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/SalesConsultant/SalesConsultantTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Address/AddressAssertion.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/BaseAssertion.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Cnpj/CnpjAssertion.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Cpf/CpfAssertion.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Customer/CustomerAssertion.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Email/EmailAssertion.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Manager/ManagerAssertion.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Phone/PhoneAssertion.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Price/PriceAssertion.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/SalesConsultant/SalesConsultantAssertion.cs
Labels: enhancement

#25 feature/create-shipping-aggregate-root
  .github/dependabot.yml
  src/Orderly.Domain/Shipping/Shipping.cs
  src/Orderly.Domain/Shipping/Validators/ShippingValidator.cs
  src/Orderly.Domain/Shipping/ValueObjects/ShippingId.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Shipping/ShippingTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Shipping/ValueObjects/ShippingIdTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Shipping/ShippingAssertion.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Shipping/ShippingFixture.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Shipping/ShippingGenerator.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/ShippingId/ShippingIdAssertion.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/ShippingId/ShippingIdFixture.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/ShippingId/ShippingIdGenerator.cs
Labels: new feature

#27 feature/create-discount-value-object
  src/Orderly.Domain/Order/Validators/DiscountValidator.cs
  src/Orderly.Domain/Order/ValueObjects/Discount.cs
  src/Orderly.Domain/Validation/ValidationRules.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Order/ValueObjects/DiscountTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Discount/DiscountAssertion.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Discount/DiscountFixture.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Discount/DiscountGenerator.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/ShippingId/ShippingIdAssertion.cs
Labels: new feature

#26 feature/create-product-aggregate-root
  src/Orderly.Domain/Orderly.Domain.csproj
  src/Orderly.Domain/Product/Product.cs
  src/Orderly.Domain/Product/Validators/ProductValidator.cs
  src/Orderly.Domain/Product/ValueObjects/ProductId.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Product/ProductTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Product/ValueObjects/ProductIdTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Product/ProductAssertion.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Product/ProductFixture.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Product/ProductGenerator.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/ProductId/ProductIdAssertion.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/ProductId/ProductIdFixture.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/ProductId/ProductIdGenerator.cs
Labels: new feature

#35 Remove assert exception from files.
  tests/UnitTests/Orderly.Domain.UnitTests/Order/ValueObjects/DiscountTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Product/ProductTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Shipping/ShippingTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Discount/DiscountAssertion.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Product/ProductAssertion.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Shipping/ShippingAssertion.cs
Labels: bug

#34 Add sealed on classes.
  src/Orderly.Domain/Manager/Manager.cs
  src/Orderly.Domain/Manager/Validators/ManagerValidator.cs
  src/Orderly.Domain/Manager/ValueObjects/ManagerId.cs
  src/Orderly.Domain/Order/Validators/DiscountValidator.cs
  src/Orderly.Domain/Order/ValueObjects/Discount.cs
  src/Orderly.Domain/Product/Product.cs
  src/Orderly.Domain/Product/Validators/ProductValidator.cs
  src/Orderly.Domain/Product/ValueObjects/ProductId.cs
  src/Orderly.Domain/SalesConsultant/SalesConsultant.cs
  src/Orderly.Domain/SalesConsultant/Validators/SalesConsultantValidator.cs
  src/Orderly.Domain/Shipping/Shipping.cs
  src/Orderly.Domain/Shipping/Validators/ShippingValidator.cs
  src/Orderly.Domain/Shipping/ValueObjects/ShippingId.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Manager/ManagerTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Order/ValueObjects/DiscountTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Product/ProductTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Product/ValueObjects/ProductIdTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Shipping/ShippingTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Shipping/ValueObjects/ShippingIdTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Discount/DiscountAssertion.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Discount/DiscountFixture.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Discount/DiscountGenerator.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Product/ProductAssertion.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Product/ProductFixture.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Product/ProductGenerator.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/ProductId/ProductIdAssertion.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/ProductId/ProductIdFixture.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/ProductId/ProductIdGenerator.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Shipping/ShippingAssertion.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Shipping/ShippingFixture.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Shipping/ShippingGenerator.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/ShippingId/ShippingIdAssertion.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/ShippingId/ShippingIdFixture.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/ShippingId/ShippingIdGenerator.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Validation/ValidationRulesTest.cs
Labels: bug

#38 Add generate and restore on ManagerId.cs and ShippingId.cs
  src/Orderly.Domain/Manager/Manager.cs
  src/Orderly.Domain/Manager/ValueObjects/ManagerId.cs
  src/Orderly.Domain/Shipping/Shipping.cs
  src/Orderly.Domain/Shipping/ValueObjects/ShippingId.cs
Labels: bug

#37 fix/add-restore-generate-in-interfaces
  src/Orderly.Domain/Product/ValueObjects/ProductId.cs
  src/Orderly.Domain/SalesConsultant/SalesConsultant.cs
  src/Orderly.Domain/SalesConsultant/ValueObjects/SalesConsultantId.cs
Labels: bug

#39 Created base structure of the application layer
  Orderly.sln
  src/Orderly.Application/Orderly.Application.csproj
  src/Orderly.Application/UseCase/Customer/CreateCustomer/CreateCustomerInput.cs
  src/Orderly.Application/UseCase/Customer/CreateCustomer/CreateCustomerOutput.cs
  src/Orderly.Application/UseCase/Customer/CreateCustomer/CreateCustomerUseCase.cs
  src/Orderly.Application/UseCase/Customer/GetCustomer/GetCustomerInput.cs
  src/Orderly.Application/UseCase/Customer/GetCustomer/GetCustomerOutput.cs
  src/Orderly.Application/UseCase/Customer/GetCustomer/GetCustomerUseCase.cs
  src/Orderly.Application/UseCase/IUnitOfWork.cs
  src/Orderly.Application/UseCase/IUseCase.cs
  src/Orderly.Domain/Customer/Customer.cs
  src/Orderly.Domain/Customer/ICustomerRepository.cs
  src/Orderly.Domain/Customer/ValueObjects/CustomerId.cs
  src/Orderly.Domain/SalesConsultant/ISalesConsultantRepository.cs
  src/Orderly.Domain/SeedWork/IRepository.cs
  src/Orderly.Domain/SeedWork/IUnitOfWork.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Customer/CustomerFixture.cs
Labels: new feature

#41 Add manager use case.
  src/Orderly.Application/UseCase/Customer/CreateCustomer/CreateCustomerUseCase.cs
  src/Orderly.Application/UseCase/Customer/GetCustomer/GetCustomerUseCase.cs
  src/Orderly.Application/UseCase/Manager/CreateManager/CeateManagerInput.cs
  src/Orderly.Application/UseCase/Manager/CreateManager/CreateManagerOutput.cs
  src/Orderly.Application/UseCase/Manager/CreateManager/CreateManagerUseCase.cs
  src/Orderly.Application/UseCase/Manager/DeleteManager/DeleteManagerInput.cs
  src/Orderly.Application/UseCase/Manager/DeleteManager/DeleteManagerOutput.cs
  src/Orderly.Application/UseCase/Manager/DeleteManager/DeleteManagerUseCase.cs
  src/Orderly.Application/UseCase/Manager/GetManager/GetManagerInput.cs
  src/Orderly.Application/UseCase/Manager/GetManager/GetManagerOutput.cs
  src/Orderly.Application/UseCase/Manager/GetManager/GetManagerUseCase.cs
  src/Orderly.Domain/Common/ValueObjects/Address.cs
  src/Orderly.Domain/Manager/IManagerRepository.cs
  src/Orderly.Domain/Manager/Manager.cs
  src/Orderly.Domain/SeedWork/IRepository.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Manager/ManagerFixture.cs
Labels: new feature

#40 feature/create-sales-consultant-use-case
  src/Orderly.Application/UseCase/SalesConsultant/CreateSalesConsultant/CreateSalesConsultantInput.cs
  src/Orderly.Application/UseCase/SalesConsultant/CreateSalesConsultant/CreateSalesConsultantOutput.cs
  src/Orderly.Application/UseCase/SalesConsultant/CreateSalesConsultant/CreateSalesConsultantUseCase.cs
  src/Orderly.Application/UseCase/SalesConsultant/DeleteSalesConsultant/DeleteSalesConsultantInput.cs
  src/Orderly.Application/UseCase/SalesConsultant/DeleteSalesConsultant/DeleteSalesConsultantOutput.cs
  src/Orderly.Application/UseCase/SalesConsultant/DeleteSalesConsultant/DeleteSalesConsultantUseCase.cs
  src/Orderly.Application/UseCase/SalesConsultant/GetSalesConsultant/GetSalesConsultantInput.cs
  src/Orderly.Application/UseCase/SalesConsultant/GetSalesConsultant/GetSalesConsultantOutput.cs
  src/Orderly.Application/UseCase/SalesConsultant/GetSalesConsultant/GetSalesConsultantUseCase.cs
  src/Orderly.Domain/SalesConsultant/SalesConsultant.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/SalesConsultant/SalesConsultantFixture.cs
Labels: new feature

#45 Edit EmailFixture.cs and EmailTest.cs. Exclude EmailAssertion.cs and …
  tests/UnitTests/Orderly.Domain.UnitTests/Common/ValueObjects/EmailTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Constants/Constants.Email.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Email/EmailAssertion.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Email/EmailFixture.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Email/EmailGenerator.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Validation/ValidationRulesTest.cs
Labels: bug, enhancement

#47 Fix/cpf and cnpj format
  tests/UnitTests/Orderly.Domain.UnitTests/Common/ValueObjects/CnpjTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Common/ValueObjects/CpfTest.cs
Labels: bug

#50 Fix/edit price fixture and price test
  tests/UnitTests/Orderly.Domain.UnitTests/Common/ValueObjects/EmailTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Common/ValueObjects/PriceTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Constants/Constants.Price.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Price/PriceAssertion.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Price/PriceFixture.cs
  tests/UnitTests/Orderly.Domain.UnitTests/TestUtils/Price/PriceGenerator.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Validation/ValidationRulesTest.cs
Labels: bug

#46 Add UntimmedEmail at EmailTest.cs
  tests/UnitTests/Orderly.Domain.UnitTests/Common/ValueObjects/EmailTest.cs
Labels: bug

#51 Fix/add format email test
  tests/UnitTests/Orderly.Domain.UnitTests/Common/ValueObjects/EmailTest.cs
Labels: bug

#48 Fix/application layer fixes
  src/Orderly.Application/UseCase/Customer/CreateCustomer/CreateCustomerInput.cs
  src/Orderly.Application/UseCase/Customer/CreateCustomer/CreateCustomerOutput.cs
  src/Orderly.Application/UseCase/Customer/CreateCustomer/CreateCustomerUseCase.cs
  src/Orderly.Application/UseCase/Customer/GetCustomer/GetCustomerInput.cs
  src/Orderly.Application/UseCase/Customer/GetCustomer/GetCustomerOutput.cs
  src/Orderly.Application/UseCase/IUnitOfWork.cs
  src/Orderly.Application/UseCase/IUseCase.cs
  src/Orderly.Application/UseCase/Manager/CreateManager/CeateManagerInput.cs
  src/Orderly.Application/UseCase/Manager/CreateManager/CreateManagerOutput.cs
  src/Orderly.Application/UseCase/Manager/CreateManager/CreateManagerUseCase.cs
  src/Orderly.Application/UseCase/Manager/DeleteManager/DeleteManagerInput.cs
  src/Orderly.Application/UseCase/Manager/DeleteManager/DeleteManagerOutput.cs
  src/Orderly.Application/UseCase/Manager/DeleteManager/DeleteManagerUseCase.cs
  src/Orderly.Application/UseCase/Manager/GetManager/GetManagerInput.cs
  src/Orderly.Application/UseCase/Manager/GetManager/GetManagerOutput.cs
  src/Orderly.Application/UseCase/Manager/GetManager/GetManagerUseCase.cs
  src/Orderly.Application/UseCase/SalesConsultant/CreateSalesConsultant/CreateSalesConsultantUseCase.cs
  src/Orderly.Application/UseCase/SalesConsultant/DeleteSalesConsultant/DeleteSalesConsultantUseCase.cs
  src/Orderly.Application/UseCase/SalesConsultant/GetSalesConsultant/GetSalesConsultantUseCase.cs
Labels: enhancement
